# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SxqMQ3Il94Ebvgd1jhjpo4hoVpd3qFfv
"""

!pip install --upgrade --ignore-installed kaggle

from google.colab import files
files.upload()

!mkdir ~/.kaggle #created at root folder in colab

#copy
!cp kaggle.json ~/.kaggle

! chmod 600 ~/.kaggle/kaggle.json

countries=!kaggle datasets download -d thomaskranzkowski/using-geodata-in-python

"""Sorting countries by population:"""

ax=countries.sort_values('pop_est').plot('pop_est', cmap='plasma', figsize=(30, 20), legend=True)
ax.set_title("worldmap", fontsize=40)

"""Visualizing GDP:"""

ax=countries.sort_values('gdp_md_est').plot('gdp_md_est', cmap='viridis', figsize=(30, 20),legend=True)
ax.set_title("worldmap", fontsize = 40)

africa=countries[countries['continent']=='Africa']
africa['name']

"""Sorting countries by overall GDP:"""

import warnings
warnings.filterwarnings("ignore")

africa=countries[countries['continent']=='Africa']
africa.sort_values('gdp_md_est').plot('gdp_md_est', cmap='viridis',scheme='equal_interval', k=10, figsize=(15, 10),legend=True)

print('highest overall gdp in africa:')
africa.loc[africa['gdp_md_est'].idxmax()]

"""Add column gdp/capita:"""

africa['gdp/pop'] = (africa.gdp_md_est / africa.pop_est)

africa

africa.sort_values('gdp/pop').plot('gdp/pop', cmap='viridis',scheme='equal_interval', k=10, figsize=(15, 10),legend=True)

print('highest gdp per capita:')
africa.loc[africa['gdp/pop'].idxmax()]

"""Agglomorative clustering:"""

import sklearn.cluster as skc
from sklearn.cluster import AgglomerativeClustering
africa_gdpclusters = AgglomerativeClustering(n_clusters=4).fit(africa[['gdp/pop']])
africa.assign(labels=africa_gdpclusters.labels_).plot('labels', cmap='plasma', figsize=(15, 10), legend=True)

"""Kmeans clustering:"""

from sklearn.cluster import KMeans 
africa_gdpclusters2 = KMeans(n_clusters=4).fit(africa[['gdp/pop']])
africa.assign(labels=africa_gdpclusters2.labels_).plot('labels', cmap='viridis', figsize=(15, 10), legend=True)

africa_gdpclusters2.score

africa_gdpclusters2.cluster_centers_

africa_gdpclusters2.labels_

cluster = africa_gdpclusters2.labels_

cluster

africa['cluster'] = cluster

africa

clafrica = pd.DataFrame(africa)

cluster_1 = clafrica.loc[africa['cluster']== 1]

cluster_1.name

clafrica.name